version: '3.8'

services:
  tortoise-api:
    build: .
    image: tortoise-tts-api
    container_name: tortoise-api
    ports:
      - "8000:8000"
    environment:
      - TORTOISE_MODELS_DIR=/models
    volumes:
      - /mnt/user/data/tortoise_tts/models:/models
      - /mnt/user/data/tortoise_tts/results:/results
      - /mnt/user/data/.cache/huggingface:/root/.cache/huggingface
      - /root:/work
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
